-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE FUNCTION bookmark_movie(movie_row movies, user_id int)
-- RETURNS boolean AS $$
-- BEGIN
--     RETURN EXISTS (
--         SELECT 1
--         FROM bookmarks A
--         WHERE A.user = user_id AND A.movie_id = movie_row.id
--     );
-- END;
-- $$ LANGUAGE plpgsql STABLE;
